# Generated by Django 5.2.8 on 2025-11-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('customer_id', models.IntegerField(help_text='Enter you id')),
                ('customer_email', models.CharField(help_text='enter your email')),
                ('dob', models.DateField()),
            ],
        ),
    ]
